apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAy8v12hWg8tEuUfKyCnXAbrKkdw8TxxLiHmA/4ndOP9aqgm4YnDhHJhEDPocGUHbUk2B7t3Jz6vNDHQfNGUXqicCiCXzi8XeIXrX3hpwKuX7bIBVOadYrssq+Vehni3uajiuw7tEv6Y/N4dPRG2puIRfD5z8U2hvLbAVnaeQM1UZvUr5JGUnMGynF41czLIT8oaj4F56DrulTQ7Bwhm+/u8+Kc2oka7DBy/CmU7aYEHbzv+0uYpQpKfm/6g7Re5eVAD7plqS5H42DIA861LlZQkYu3KgJXSlm+yjTc+ZzQTAihXPMWEIerMvS/qGBRSjw0WQlMkRoYEekNDLttkCiKN1mtC49tvGwHgH/bcsUNIx3DaHJ6OJKvQgZIig/zb8zqhBA6w1vL4NH93hHtf6c7NeiqbNEtGtg5agoweWUZaZSkOtHrkEbQG/cgHyd+vqbZUSybcl6sp66VouD7QF/yBzwYZEw1KQ/HVK4S+bQkMYtDzt1sCZx4U9d/IwTD0rrkQmjJRdSjXP7LTmLAtlxxmvzWPyvWgcJyguPI9toMfOAX/XsW6GXEZnDdcbb6Bzws84bbOIddgsI8n0i3AO1AMWX60GK0rMzN1k0xAJXH4Ln/8LQlYhsuyja1Uloaz2tr83m+9fmz64AcC65ymRkecO+4rtmDXTb8iqZBuXf9kObZ3aOa5AfLPWL5kjZTgUxGVg4VvEK+cbBf1MAJOkJBYHwRuyHmVnX0KI7A1V9ZKN32yugFCIWV
    username: AgC4rjKD9H0cRn2rGBC96ACbRiXloxnxoYXtBvmfJR5Gka4JZSrg3tzSZo5a4SkbevY1UsjLOVd8dHuYznsCZApLUXzSV4pG+25ND+QcHcHxY1e880r1+4bGPli7ubXhJ2zIRyvFUKOqcjlucVTnucDONstkmZSnDvmp9zS8sHg7DzxxJjVQs7wj7bstgQKTwSBNRpZpefuLP+YA1HjHirwVkL88bwlYR/a6eSAzu49fIy+NY5bMn/4FUp+xWcn1vDKf5j3knV51fcdbwvWtjawBUC2hIiK4ewApaQmMgWNS/U41zx32c9oS0RPuuI7moBr8B5y59/1Yj3+1qf6ejxz/xMMrZQuM4mxXoP9adcwuwllj7XbmibsOrnkUSnqXreXU0dgquFmZEB68pE1Iw2TSKtWw4NbkKjf1nhSdr1yfDRlXdD7gqUn1V681WH05AATLvgcxoAFt/E2VzajIQ0W+3+wT3WR1mDYqMBuxNRX49A4L158Qh5ETf9W5HtvhzcKxNsLtKnXzGDRzpqsfIh7djQ9eHpeEC+yeLWy06GUEJH1hJDMNAO4Rvm4d8bL9sCMdaPxuSjYiSgdXTqD2Humk1rVq0/dSldkUBzbfJxYeENCwxDVqL+tpKyUZNZRd3VtI7Seunl2WC/uX1UukUCr0hgVO/fYCc7Jw18JCqTnyGAzKbppxKEr9OooWp/9UU00hTN65o+4/CA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

