apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  license:
    # License info https://www.ibm.com/docs/en/app-connect/containers_cd?topic=resources-licensing-reference-app-connect-operator
    license: L-KSBM-C37J2R
    use: CloudPakForIntegrationProduction
  replicas: 2
  pod:
    containers:
      runtime:
        image: default-route-openshift-image-registry.apps.labo3.poc.com/ci/create-customer-details-rest:fe86f697ce71b2712871ccdc973ac70e6fbb107d
