kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: el-ace-integration-server-gitlab
spec:
  to:
    kind: Service
    name: el-ace-integration-server-gitlab
  port:
    targetPort: https-listener
  tls:
    termination: passthrough
  wildcardPolicy: None

