apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-APEH-CJUCNR
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 12.0.7.0-r1
  adminServerSecure: true
  pod:
    containers:
      runtime:
        image: default-route-openshift-image-registry.apps.labo3.poc.com/ci/create-customer-details-rest:9c2463aa582000e0ff80c6ae2575f8f18d0448ae
        imagePullPolicy: Always
  configurations:
    - create-customer-serverconf.yaml
    - create-customer-policy
