apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  replicas: 2
  pod:
    containers:
      runtime:
        image: default-route-openshift-image-registry.apps.labo3.poc.com/ci/create-customer-details-rest:724b75201622b7edbc2a85f57742e4de3d2d85d9
