apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: create-customer-details-rest
spec:
  replicas: 4
  pod:
    containers:
      runtime:
        image: default-route-openshift-image-registry.apps.labo3.poc.com/ci/create-customer-details-rest:bb40193ba2cc938da83804760df2812c1bc6f543
