apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-integration-server-gitlab
spec:
  params:
    - name: source-repo
      description: name of the repository
    - name: path_with_namespace
      description: path to gitlab repo
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: ace-integration-server-$(tt.params.source-repo)-
        namespace: ci
      spec:
        params:
          - name: is-source-repo-url
            value: git@gitlab.poc.com:$(tt.params.path_with_namespace).git
          - name: is-infra-repo-url
            value: git@github.com:labnetorg/ace-infra.git
          - name: git-ops-repo-url
            value: git@github.com:labnetorg/multi-tenancy-gitops-apps.git
          - name: gitops-apps-repo-full-name
            value: labnetorg/multi-tenancy-gitops-apps
          - name: github-pr-token-secret-name
            value: cicd-unai
        pipelineRef:
          name: ace-integration-server
        serviceAccountName: pipeline
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: ace-integration-server
          - name: ace-infra-repo-secret
            secret:
              secretName: ace-infra-at-github
          - name: gitops-repo-secret
            secret:
              secretName: multi-tenancy-gitops-apps-at-github
          - name: ace-source-repo-secret
            secret:
              secretName: $(tt.params.source-repo)-at-gitlab