apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-promote-dev-stage
spec:
  params:
  - default: git@github.com:labnetorg/create-customer.git
    name: is-source-repo-url
    description: "SSH url of ACE source repository, ex: git@github.com:ace-prod-ref/create-customer.git"
    type: string
  - default: is-source
    name: is-source-directory
    type: string
  - description: Points to the dev/staging env
    name: source-env
    type: string
    default: dev
  - description: Points to the staging/prod env
    name: destination-env
    type: string
    default: staging


  tasks:

  - name: clone-is-source
    params:
      - name: url
        value: $(params.is-source-repo-url)
      - name: subdirectory
        value: $(params.is-source-directory)
      - name: deleteExisting
        value: "true"
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: shared-workspace
      - name: ssh-directory
        workspace: ace-source-repo-secret

  - name: resolve-props
    params:
    - name: is-source-directory
      value: $(params.is-source-directory)
    runAfter:
    - clone-is-source
    taskRef:
      kind: Task
      name: resolve-props
    workspaces:
    - name: input
      workspace: shared-workspace

  - name: functional-test
    params:
    - name: source-env
      value: $(params.source-env)
    - name: is-source-directory
      value: $(params.is-source-directory)
    - name: release-name
      value: create-customer-details-rest
    - name: endpoint-path
      value: createcustomerrestcallingws/v1/createcustomer
    runAfter:
    - resolve-props
    taskRef:
      kind: Task
      name: functional-test
    workspaces:
    - name: workspace
      workspace: shared-workspace


  - name: gitops-for-ace
    params:
    - name: source-env
      value: $(params.source-env)
    - name: destination-env
      value: $(params.destination-env)
    - name: git-pr
      value: "true"
    runAfter:
    - functional-test
    taskRef:
      kind: Task
      name: ibm-gitops-for-ace
      
  workspaces:
  - name: shared-workspace
  - name: ace-source-repo-secret
